version: '3.4'

services:
  postgres:
    container_name: Postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "291203"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  tms.notes.service:
    image: tms_notes_service
    build:
      context: .
      dockerfile: src/TMS.Notes.Service/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    restart: always

volumes:
  postgres-data:

